export const PLAY_PAUSE = 'PLAY_PAUSE';
export const TOGGLE_NOTE = 'TOGGLE_NOTE';
export const CHANGE_INSTRUMENT = 'CHANGE_INSTRUMENT';
export const UPDATE_PLAYBACK_TIME = 'UPDATE_PLAYBACK_TIME';
export const SET_CLIENT_IS_LOADED = 'SET_CLIENT_IS_LOADED';
